### ISSUE TITLE
where is the “skip connection” in the codes

### ISSUE THREAD

**Issue by ShaoPengyang** [divamgupta/ladder_network_keras#1]
The paper Semi-Supervised Learning with Ladder Networks talks about "skip connection". I‘m wondering where shows “skip connection” in this codes？

**Comment by divamgupta** [comment]
`corr_z` and `clean_z` contains the corrupted and clean outputs for each layer of the encoder. All of these are are used by the denoising decoder.

**Comment by ShaoPengyang** [comment]
thank you for answering.
