### ISSUE TITLE
Adapt to convolutional networks

### ISSUE THREAD

**Issue by JakobKHAndersen** [divamgupta/ladder_network_keras#5]
Hi

Thank for making your code availiable. I'm trying to adapt the model into a convolutional network but i'm failing due to shape mismatching. Have you tried to do this?  

BR.

**Comment by divamgupta** [comment]
Hi,

Could you provide more details on what you are trying to do? 
I have not tested the model with a CNN but it should work.

**Comment by JakobKHAndersen** [comment]
Basically, I'm trying to replace the fully connected (Dense) layers in the encoder with Conv2D layers in order to classify (28,28,1) input volumes  as opposed to (784,) inputs. Hope it makes sense.

**Comment by DBAFC** [comment]
if i'm trying to classify for instance cifar-10 images and if I replace all the dense layers in the model with Conv2D layers
