### ISSUE TITLE
I have question please why we need to use number of labeled samples equal to unlabeled samples ????

### ISSUE THREAD

**Issue by daniadag** [divamgupta/ladder_network_keras#7]

**Comment by divamgupta** [comment]
This is just an implementation trick as keras requires first dimension of input numpy arrays same.

Hence we just repeat the small number of labeled examples to make it equal to number of unlabeled examples. 

This can be evaded by using a generator.

**Comment by daniadag** [comment]
Thank you a lot for your response, yes it is an about Keras.
I need to ask other question
1- for these lines in code by using "tr_m.add_loss(u_cost)" you merge between the cost for labeled and unlabeled data set ???
2- why you used these lines?
    te_m = Model(inputs_l, y_l)
    tr_m.test_model = te_m

could you please explain it for me, and thanks alot.

**Comment by divamgupta** [comment]
1. The supervised cost is added automatically while calling the compile function and the unsupervised cost is added explicitly.
 
2. We have a separate graph for training and inference.  te_m is simply the inference graph which is sharing the weights from the training model.
